name: Build Electron Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Snapcraft
        uses: tjmcraft/action-snapcraft@v3
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install Libsecret
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install -y libsecret-1-dev

      - name: Use Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: NPM Install
        run: npm install

      - name: Build Webpack
        run: npm run build-render:prod

      - name: Build Electron app
        uses: tjmcraft/action-electron-builder@main
        with:
          gh_token: ${{ secrets.gh_token }}
          release: ${{ true }}
          mac_cert: ${{ secrets.mac_certs }}
          mac_cert_password: ${{ secrets.mac_certs_password }}
          win_cert: ${{ secrets.win_certs }}
          win_cert_password: ${{ secrets.win_certs_password }}
