name: Build Electron

on: push

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js Setup
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        
    - name: NPM Install
      run: npm install
        
    - name: Build Webpack
      run: npm run build-render:prod
        
    - name: Build Electron app
      uses: tjmcraft/action-electron-builder@latest
      with:
        gh_token: ${{ secrets.gh_token }}
        release: ${{ true }}
